//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCUnitTest.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBase64Binary", Namespace="http://abbyy/", ItemName="base64Binary")]
    [System.SerializableAttribute()]
    public class ArrayOfBase64Binary : System.Collections.Generic.List<byte[]> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonData", Namespace="http://abbyy/")]
    [System.SerializableAttribute()]
    public partial class PersonData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FCUnitTest.ServiceReference1.ProcessInfo processInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FCUnitTest.ServiceReference1.ArrayOfChar NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FCUnitTest.ServiceReference1.ArrayOfChar DateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public FCUnitTest.ServiceReference1.ProcessInfo processInfo {
            get {
                return this.processInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.processInfoField, value) != true)) {
                    this.processInfoField = value;
                    this.RaisePropertyChanged("processInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public FCUnitTest.ServiceReference1.ArrayOfChar Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public FCUnitTest.ServiceReference1.ArrayOfChar Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessInfo", Namespace="http://abbyy/")]
    [System.SerializableAttribute()]
    public partial class ProcessInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int processNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorField;
        
        private int freeProcCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestGUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int processNumber {
            get {
                return this.processNumberField;
            }
            set {
                if ((this.processNumberField.Equals(value) != true)) {
                    this.processNumberField = value;
                    this.RaisePropertyChanged("processNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string error {
            get {
                return this.errorField;
            }
            set {
                if ((object.ReferenceEquals(this.errorField, value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int freeProcCount {
            get {
                return this.freeProcCountField;
            }
            set {
                if ((this.freeProcCountField.Equals(value) != true)) {
                    this.freeProcCountField = value;
                    this.RaisePropertyChanged("freeProcCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RequestGUID {
            get {
                return this.RequestGUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestGUIDField, value) != true)) {
                    this.RequestGUIDField = value;
                    this.RaisePropertyChanged("RequestGUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfChar", Namespace="http://abbyy/", ItemName="char")]
    [System.SerializableAttribute()]
    public class ArrayOfChar : System.Collections.Generic.List<char> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://abbyy/", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name documentDifinition from namespace http://abbyy/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://abbyy/GetResultFromImages", ReplyAction="*")]
        FCUnitTest.ServiceReference1.GetResultFromImagesResponse GetResultFromImages(FCUnitTest.ServiceReference1.GetResultFromImagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://abbyy/GetResultFromImages", ReplyAction="*")]
        System.Threading.Tasks.Task<FCUnitTest.ServiceReference1.GetResultFromImagesResponse> GetResultFromImagesAsync(FCUnitTest.ServiceReference1.GetResultFromImagesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultFromImagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultFromImages", Namespace="http://abbyy/", Order=0)]
        public FCUnitTest.ServiceReference1.GetResultFromImagesRequestBody Body;
        
        public GetResultFromImagesRequest() {
        }
        
        public GetResultFromImagesRequest(FCUnitTest.ServiceReference1.GetResultFromImagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://abbyy/")]
    public partial class GetResultFromImagesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] documentDifinition;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public FCUnitTest.ServiceReference1.ArrayOfBase64Binary images;
        
        public GetResultFromImagesRequestBody() {
        }
        
        public GetResultFromImagesRequestBody(byte[] documentDifinition, FCUnitTest.ServiceReference1.ArrayOfBase64Binary images) {
            this.documentDifinition = documentDifinition;
            this.images = images;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResultFromImagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResultFromImagesResponse", Namespace="http://abbyy/", Order=0)]
        public FCUnitTest.ServiceReference1.GetResultFromImagesResponseBody Body;
        
        public GetResultFromImagesResponse() {
        }
        
        public GetResultFromImagesResponse(FCUnitTest.ServiceReference1.GetResultFromImagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://abbyy/")]
    public partial class GetResultFromImagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FCUnitTest.ServiceReference1.PersonData[] GetResultFromImagesResult;
        
        public GetResultFromImagesResponseBody() {
        }
        
        public GetResultFromImagesResponseBody(FCUnitTest.ServiceReference1.PersonData[] GetResultFromImagesResult) {
            this.GetResultFromImagesResult = GetResultFromImagesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : FCUnitTest.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<FCUnitTest.ServiceReference1.WebService1Soap>, FCUnitTest.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FCUnitTest.ServiceReference1.GetResultFromImagesResponse FCUnitTest.ServiceReference1.WebService1Soap.GetResultFromImages(FCUnitTest.ServiceReference1.GetResultFromImagesRequest request) {
            return base.Channel.GetResultFromImages(request);
        }
        
        public FCUnitTest.ServiceReference1.PersonData[] GetResultFromImages(byte[] documentDifinition, FCUnitTest.ServiceReference1.ArrayOfBase64Binary images) {
            FCUnitTest.ServiceReference1.GetResultFromImagesRequest inValue = new FCUnitTest.ServiceReference1.GetResultFromImagesRequest();
            inValue.Body = new FCUnitTest.ServiceReference1.GetResultFromImagesRequestBody();
            inValue.Body.documentDifinition = documentDifinition;
            inValue.Body.images = images;
            FCUnitTest.ServiceReference1.GetResultFromImagesResponse retVal = ((FCUnitTest.ServiceReference1.WebService1Soap)(this)).GetResultFromImages(inValue);
            return retVal.Body.GetResultFromImagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FCUnitTest.ServiceReference1.GetResultFromImagesResponse> FCUnitTest.ServiceReference1.WebService1Soap.GetResultFromImagesAsync(FCUnitTest.ServiceReference1.GetResultFromImagesRequest request) {
            return base.Channel.GetResultFromImagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FCUnitTest.ServiceReference1.GetResultFromImagesResponse> GetResultFromImagesAsync(byte[] documentDifinition, FCUnitTest.ServiceReference1.ArrayOfBase64Binary images) {
            FCUnitTest.ServiceReference1.GetResultFromImagesRequest inValue = new FCUnitTest.ServiceReference1.GetResultFromImagesRequest();
            inValue.Body = new FCUnitTest.ServiceReference1.GetResultFromImagesRequestBody();
            inValue.Body.documentDifinition = documentDifinition;
            inValue.Body.images = images;
            return ((FCUnitTest.ServiceReference1.WebService1Soap)(this)).GetResultFromImagesAsync(inValue);
        }
    }
}
